#!/bin/bash

# Get current script path
SCRIPT_PATH="$( dirname -- "$( readlink -f -- "${0}"; )"; )"
# Activate OctoDNS Python venv
source "${SCRIPT_PATH}/common.sh"

SOURCES="octodns_route53/*.py setup.py tests/*.py"

pyflakes $SOURCES
