#!/bin/bash

# Get current script path
SCRIPT_PATH="$( dirname -- "$( readlink -f -- "${0}"; )"; )"
# Activate OctoDNS Python venv
source "${SCRIPT_PATH}/common.sh"

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=

pytest --disable-network "$@"
